### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by KhairulAzmi21** [balping/ticketit-app#1]
how do i change language ? I try to change summernote locale but it didnot do anything

<img width="1177" alt="screen shot 2017-03-22 at 4 09 38 pm" src="https://cloud.githubusercontent.com/assets/12378983/24187897/16092694-0f1a-11e7-98b0-c8116aed8853.png">

**Comment by balping** [comment]
In `config/app.php` set the locale parameter.

Please note that only these languages are supported: https://github.com/thekordy/ticketit/tree/0.2/src/Translations

And you will need to localise registration, login, password reset by yourself (by updating view files)
