### ISSUE TITLE
How create Agent?

### ISSUE THREAD

**Issue by luizpatrocinio** [balping/ticketit-app#11]
Hi,

Good work! But how create account for agent

Tks.

**Comment by luizpatrocinio** [comment]
Sorry in the /register

Tks

**Comment by luizpatrocinio** [comment]
Would not it be better to be seen only by the admin?

Tks.

**Comment by balping** [comment]
No, I don't think so. Registering users should not be part of ticketit. You can disable public registration quite easily and can add an admin-only form to add new users. You can use `Kordy\Ticketit\Middleware\IsAdminMiddleware` to limit access to admins for any route.
