### ISSUE TITLE
Issue with routing

### ISSUE THREAD

**Issue by ashishscrm** [balping/ticketit-app#2]
InvalidArgumentException in UrlGenerator.php line 337: Action Kordy\Ticketit\Controllers\TicketsController@index not defined.

I am trying to install this application in IIS server without composer. I am getting above error after login page on http://localhost/ticketit/public/home route.

Please help me to resolve it.

**Comment by balping** [comment]
You should make the publlic folder to be document root

https://laravel.com/docs/master#configuration

https://laravel.com/docs/master#web-server-configuration
