### ISSUE TITLE
No panel access

### ISSUE THREAD

**Issue by rohilario** [balping/ticketit-app#9]
Although I can do the installation correctly, I can not access it through the link http://myip/ticketit/public. What can it be? I have tried the reinstallation several times and successfully, I just can not access. 

I also tried link access http://172.17.17.98:8000/ticketit/public
![2017-05-25 18](https://cloud.githubusercontent.com/assets/28963062/26466959/0f10fe96-4167-11e7-83bc-cc9fb6de32dd.png)

The installation is on a web server inside the company on the same network. Port 8000 has already been freed on the firewall

thank you.

![sem titulo](https://cloud.githubusercontent.com/assets/28963062/26466740/36ec926e-4166-11e7-8f3f-eb0563c0f38e.png)
![sem titulo2](https://cloud.githubusercontent.com/assets/28963062/26466776/5b64f01e-4166-11e7-9459-2f823dfb2930.png)
![sem titulo3](https://cloud.githubusercontent.com/assets/28963062/26466806/7a59bab8-4166-11e7-9ce9-5e04c38ba0a5.png)

**Comment by balping** [comment]
First, you are using port 8000 and not 80, you should connect to yourip:8000. You also need to check that port 8000 is open on your server. You could also consider forwarding port 80 to 8000.

Second, there's no need of concatenating `ticketit/public` to the end of the url. Using `artisan serve`, the `public` directory is made root automatically.

**Comment by rohilario** [comment]
I tried using the artisan server through port 8000 and it did not, but my project is installed on apache web server that I have hosted my site, so should also go through port 80 ..

Ports 8000 and 80 are open on the server.

Again, thanks for the reply.

**Comment by balping** [comment]
If you're using apache, you should set the document root to the public folder and it should work. 

https://laravel.com/docs/5.4#web-server-configuration

**Comment by rohilario** [comment]
Apache module is enabled and I configured the .htacess, without success. The ticketit folder is at the root of the server.

![image](https://cloud.githubusercontent.com/assets/28963062/26499433/00e0467c-4209-11e7-8637-0de048ac4c61.png)


![image](https://cloud.githubusercontent.com/assets/28963062/26498442/7376f9d2-4205-11e7-8bbd-21896a526aa7.png)


Anyway, thank you.

**Comment by balping** [comment]
You should set the apache document root to that folder.

Usual place to do that is `/etc/apache2/sites-enabled/000-default.conf`

E.g.

```
<VirtualHost *:80>
        # ...
        DocumentRoot /web/ticketit/public

        <Directory "/web/ticketit/public">
                AllowOverride All
        </Directory>

        # ...
</VirtualHost>
```

**Comment by rohilario** [comment]
Still unsuccessful. :(
If I change the line in the .httacess file RewriteRule * index.php [L] to RewriteRule ^ index.php [L] page does not get internal server error, simply does not load with error 500.

![image](https://cloud.githubusercontent.com/assets/28963062/26508649/e6b7d102-422b-11e7-9479-3599e95d6845.png)
![image](https://cloud.githubusercontent.com/assets/28963062/26508726/31dc6102-422c-11e7-8d06-e61fdfdaba1c.png)
![image](https://cloud.githubusercontent.com/assets/28963062/26508730/41b8f25c-422c-11e7-9a3a-543abc4e662f.png)
![image](https://cloud.githubusercontent.com/assets/28963062/26508743/49c811b2-422c-11e7-9907-87f3c7216ee0.png)

**Comment by balping** [comment]
After you have set documentroot, that folder is `/`, so you should be able to access it on `yourip/`

**Comment by rohilario** [comment]
Still unsuccessful. :(
One detail of my installation is that I had to add the line "use Illuminate \ Support \ Facades \ Schema;" And "Schema :: defaultStringLength (191);" In the "AppServiceProvider.php" file for the installation to occur normally. Does it interfere with anything?

After that, I can do the installation normally without any errors. I have even re-read it several times!

![image](https://cloud.githubusercontent.com/assets/28963062/26509282/75806654-422e-11e7-92b3-0fa70b5c83a1.png)

**Comment by balping** [comment]
Now at least you get a different error - 403. Maybe the files aren't readable by apache - check permissions

**Comment by rohilario** [comment]
777 on every page...

![image](https://cloud.githubusercontent.com/assets/28963062/26509961/89cdcbf8-4231-11e7-9b43-ab1e66b9b948.png)

![image](https://cloud.githubusercontent.com/assets/28963062/26509968/958a1212-4231-11e7-9382-c217769f7991.png)

![image](https://cloud.githubusercontent.com/assets/28963062/26509993/a27dadd0-4231-11e7-9178-b4bdcfb32fa9.png)

**Comment by rohilario** [comment]
Thaaaaaaaaaaaaaaaanks!!!
![image](https://cloud.githubusercontent.com/assets/28963062/26510380/758d1f98-4233-11e7-94e4-50c438b213cc.png)

**Comment by balping** [comment]
You're welcome :-) But be careful with 777, better to set the owner to whatever user the webserver is running on and 755 for directories and 644 for files.
